export type AppointmentStatus = 'Pendente'|'Aprovado'|'Recusado'|'Reagendamento'|'Concluído'|'Cancelado'
export type Service = { id:string; name:string; description:string; duration:number; price?:number; showPrice:boolean; active:boolean; tea?:boolean }
export type Appointment = { id:string; client:string; phone:string; email?:string; serviceId:string; date:string; time:string; status:AppointmentStatus; source:string; goal?:string; notes?:string; guardian?:string; child?:string; childAge?:string; createdAt:string }
export type Review = { id:string; name:string; rating:number; comment:string; status:'Pendente'|'Aprovada'|'Oculta'; featured:boolean; demo?:boolean; createdAt:string; photo?:string }
export type Client = { id:string; name:string; phone:string; email?:string; source:string; tags:string[]; notes:string; birthDate?:string; age?:number; address?:string; neighborhood?:string; profession?:string; status?:'Ativo'|'Pausado'|'Inativo'; startDate?:string; emergencyContact?:string; planId?:string; sessionsUsed?:number; sessionsTotal?:number }
export type Anamnesis = { id:string; clientId:string; createdAt:string; updatedAt:string; status:'Rascunho'|'Finalizada'; objective:string; activityHistory:string; injuries:string; surgeries:string; pain:string; medications:string; sleep:string; routine:string; weeklyAvailability:string; observations:string; parqNotes:string; syncedToGoogle:boolean; googleSyncStatus:'Não configurado'|'Aguardando sincronização'|'Sincronizado'|'Erro'; lastGoogleSync?:string; version:number }
export type PhysicalAssessment = { id:string; clientId:string; date:string; weight?:number; height?:number; bmi?:number; bodyFat?:number; waist?:number; hip?:number; chest?:number; armRight?:number; armLeft?:number; thighRight?:number; thighLeft?:number; restingHr?:number; bloodPressure?:string; notes?:string }

export type WorkoutExercise = { id:string; name:string; muscle?:string; sets:string; reps:string; load?:string; rest?:string; cadence?:string; notes?:string; order:number }
export type Workout = { id:string; clientId:string; title:string; label:string; createdAt:string; updatedAt:string; active:boolean; version:number; exercises:WorkoutExercise[]; notes?:string }
export type Attendance = { id:string; clientId:string; date:string; status:'Compareceu'|'Faltou'|'Cancelou'|'Reagendou'; notes?:string }
export type Plan = { id:string; name:string; sessions:number; price?:number; durationDays:number; active:boolean; published?:boolean; featured?:boolean; description?:string; promoText?:string; ctaText?:string }
export type Payment = { id:string; clientId:string; planId?:string; dueDate:string; amount:number; status:'Pendente'|'Pago'|'Atrasado'; method?:string; notes?:string; paidAt?:string }

export type Availability = Record<string, { enabled:boolean; start:string; end:string; interval:number }>
export type Settings = { professionalName:string; subtitle:string; heroTitle:string; heroText:string; bio:string; education:string; cref:string; instagram:string; whatsapp:string; email:string; address:string; showPrices:boolean; pendingAlertHours:number; googleCalendarConnected:boolean; googleSheetsConnected:boolean; googleDocsConnected:boolean; googleSpreadsheetName?:string; googleDocsFolderName?:string; cancellationHours:number; accent:string; signatureName?:string; heroImage?:string; aboutImage?:string; teaImage?:string; documentLogo?:string; documentSignature?:string }
export type Store = { services:Service[]; appointments:Appointment[]; reviews:Review[]; clients:Client[]; anamneses:Anamnesis[]; physicalAssessments:PhysicalAssessment[]; availability:Availability; blockedDates:string[]; settings:Settings; workouts:Workout[]; attendances:Attendance[]; plans:Plan[]; payments:Payment[]; whatsappTemplates:{approved:string; rejected:string; reschedule:string; documentReady:string; workoutReady:string}; faqs:{id:string; q:string; a:string; tea?:boolean}[]; results:{id:string; title:string; text:string; consent:boolean; demo:boolean; image?:string}[] }
