import { useMemo, useState } from 'react'
import type { Store, Appointment } from '../../lib/types'
import { getStore, setStore, uid } from '../../lib/storage'
const weekdays=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado']
function slots(start:string,end:string,step:number){const out:string[]=[];let [h,m]=start.split(':').map(Number);const [eh,em]=end.split(':').map(Number);let a=h*60+m,b=eh*60+em;for(;a<b;a+=step)out.push(`${String(Math.floor(a/60)).padStart(2,'0')}:${String(a%60).padStart(2,'0')}`);return out}
export default function BookingForm({store,onDone}:{store:Store,onDone:(a:Appointment)=>void}){
 const [serviceId,setService]=useState(store.services.find(s=>s.active)?.id||'')
 const [date,setDate]=useState(''); const [time,setTime]=useState(''); const [form,setForm]=useState<any>({client:'',phone:'',email:'',goal:'',notes:'',source:'Instagram',guardian:'',child:'',childAge:''})
 const service=store.services.find(s=>s.id===serviceId); const day=date?weekdays[new Date(date+'T12:00:00').getDay()]:''
 const available=useMemo(()=>{if(!date||store.blockedDates.includes(date))return[];const a=store.availability[day];if(!a?.enabled)return[];const used=store.appointments.filter(x=>x.date===date&&['Pendente','Aprovado'].includes(x.status)).map(x=>x.time);return slots(a.start,a.end,a.interval).filter(x=>!used.includes(x))},[date,day,store])
 const change=(k:string,v:string)=>setForm((f:any)=>({...f,[k]:v}))
 const submit=(e:any)=>{e.preventDefault();if(!serviceId||!date||!time||!form.client||!form.phone)return alert('Preencha os campos obrigatórios.')
   const live=getStore(); if(live.appointments.some(a=>a.date===date&&a.time===time&&['Pendente','Aprovado'].includes(a.status)))return alert('Esse horário acabou de ficar indisponível. Escolha outro.')
   const a:Appointment={id:uid('apt'),client:form.client,phone:form.phone,email:form.email,serviceId,date,time,status:'Pendente',source:form.source,goal:form.goal,notes:form.notes,guardian:form.guardian,child:form.child,childAge:form.childAge,createdAt:new Date().toISOString()}
   live.appointments.unshift(a); if(!live.clients.some(c=>c.phone===form.phone)){live.clients.unshift({id:uid('cli'),name:form.client,phone:form.phone,email:form.email,source:form.source,tags:[service?.tea?'Responsável TEA':'Novo'],notes:''})};setStore(live);onDone(a)
 }
 return <form className="booking-form" onSubmit={submit}><div className="form-step"><span>01</span><h3>Escolha o serviço</h3><div className="service-options">{store.services.filter(s=>s.active).map(s=><label className={serviceId===s.id?'service-option active':'service-option'} key={s.id}><input type="radio" name="service" value={s.id} checked={serviceId===s.id} onChange={()=>{setService(s.id);setTime('')}}/><b>{s.name}</b><small>{s.duration} min</small></label>)}</div></div>
 <div className="form-step"><span>02</span><h3>Data e horário</h3><div className="grid-2"><label>Data<input type="date" value={date} min={new Date().toISOString().slice(0,10)} onChange={e=>{setDate(e.target.value);setTime('')}} required/></label><label>Horário<select value={time} onChange={e=>setTime(e.target.value)} required><option value="">Selecione</option>{available.map(x=><option key={x}>{x}</option>)}</select></label></div>{date&&!available.length&&<p className="warn">Não há horários livres nessa data.</p>}</div>
 <div className="form-step"><span>03</span><h3>Seus dados</h3><div className="grid-2"><label>Nome completo<input value={form.client} onChange={e=>change('client',e.target.value)} required/></label><label>WhatsApp<input value={form.phone} onChange={e=>change('phone',e.target.value)} placeholder="(21) 99999-9999" required/></label><label>E-mail<input type="email" value={form.email} onChange={e=>change('email',e.target.value)}/></label><label>Como conheceu?<select value={form.source} onChange={e=>change('source',e.target.value)}><option>Instagram</option><option>Indicação</option><option>Google</option><option>WhatsApp</option><option>Outro</option></select></label></div>
 {service?.tea&&<div className="tea-fields"><b>Informações do atendimento infantil</b><div className="grid-3"><label>Responsável<input value={form.guardian} onChange={e=>change('guardian',e.target.value)}/></label><label>Nome da criança<input value={form.child} onChange={e=>change('child',e.target.value)}/></label><label>Idade<input value={form.childAge} onChange={e=>change('childAge',e.target.value)}/></label></div></div>}
 <label>Objetivo principal<textarea value={form.goal} onChange={e=>change('goal',e.target.value)} rows={3}/></label><label>Observações<textarea value={form.notes} onChange={e=>change('notes',e.target.value)} rows={3}/></label></div>
 <button className="btn btn-primary btn-lg" type="submit">Solicitar agendamento</button><small className="form-note">O horário só fica confirmado após aprovação do profissional.</small></form>
}
