import { ArrowRight, CalendarCheck, HeartHandshake, ShieldCheck, Sparkles, Target, Activity, Star, Dumbbell, TimerReset, Trophy } from 'lucide-react'
import { Link } from 'react-router-dom'
import Header from '../components/layout/Header'; import Footer from '../components/layout/Footer'; import SectionTitle from '../components/site/SectionTitle'
import type { Store } from '../lib/types'
export default function Home({store}:{store:Store}){
 const approved=store.reviews.filter(r=>r.status==='Aprovada')
 const publishedPlans=store.plans.filter(p=>p.active&&p.published)
 const teaImage=store.settings.teaImage||'/images/tea-autism-pattern.png'
 return <><Header store={store}/><main>
 <section className="hero"><div className="hero-glow"/><div className="container hero-grid"><div className="hero-copy"><span className="pill"><Activity size={16}/> MOVIMENTO COM PROPÓSITO</span><h1>{store.settings.heroTitle}</h1><p>{store.settings.heroText}</p><div className="hero-actions"><Link to="/agendar" className="btn btn-primary btn-lg">Agendar avaliação <ArrowRight size={18}/></Link><a href="#servicos" className="btn btn-ghost btn-lg">Conhecer serviços</a></div><div className="hero-metrics"><div><b>01:01</b><span>Acompanhamento individual</span></div><div><b>360°</b><span>Visão de evolução</span></div><div><b>100%</b><span>Planejamento adaptável</span></div></div></div>
 <div className="hero-visual"><div className="photo-card">{store.settings.heroImage?<img className="hero-photo" src={store.settings.heroImage} alt={`Foto de ${store.settings.professionalName}`}/>:<div className="photo-placeholder"><span>FOTO PRINCIPAL</span><small>Adicione pelo painel em Imagens</small></div>}<div className="float-card fc1"><ShieldCheck/> Planejamento seguro</div><div className="float-card fc2"><CalendarCheck/> Agenda online</div></div></div></div></section>
 <section id="sobre" className="section deco-section"><div className="deco-icons"><span><Dumbbell/></span><span><TimerReset/></span><span><Trophy/></span><span><Activity/></span></div><div className="container split"><div><SectionTitle eyebrow="SOBRE" title="Treino pensado para a pessoa, não para a planilha."/><p className="lead">{store.settings.bio}</p><div className="mini-grid"><div><Target/><b>Objetivo claro</b><p>Planejamento conectado ao que realmente importa para você.</p></div><div><Sparkles/><b>Evolução consistente</b><p>Ajustes progressivos, sem atalhos ou promessas irreais.</p></div></div></div><div>{store.settings.aboutImage&&<div className="about-photo-wrap"><img src={store.settings.aboutImage} alt={`Sobre ${store.settings.professionalName}`}/></div>}<div className="dark-card"><span>FORMAÇÃO & CREDENCIAIS</span><h3>{store.settings.education}</h3><p>{store.settings.cref||'CREF e demais credenciais: preencher no painel.'}</p><div className="line"/><p>Informações profissionais permanecem editáveis e não são inventadas.</p></div></div></div></section>
 <section id="servicos" className="section alt"><div className="container"><SectionTitle eyebrow="SERVIÇOS" title="Um acompanhamento que se adapta à sua fase." text="Serviços, duração e valores podem ser gerenciados no painel." center/><div className="cards">{store.services.filter(s=>s.active).map((s,i)=><article className="service-card" key={s.id}><span className="card-index">0{i+1}</span><h3>{s.name}</h3><p>{s.description}</p>{store.settings.showPrices&&s.showPrice&&s.price?<b className="price">R$ {s.price.toFixed(2)}</b>:<span className="muted">Valor sob consulta</span>}<Link to="/agendar">Agendar <ArrowRight size={16}/></Link></article>)}</div></div></section>
 <section className="section tea-home"><div className="container tea-box tea-grid"><div className="tea-copy"><span className="eyebrow">MOVIMENTO & DESENVOLVIMENTO</span><h2>Atividade física adaptada para crianças no espectro autista.</h2><p>Uma abordagem de Educação Física individualizada, acolhedora e respeitosa, voltada ao prazer pelo movimento, coordenação, consciência corporal e autonomia — sem promessas terapêuticas.</p><div className="tea-badges"><span><HeartHandshake size={16}/> Acolhimento</span><span><Activity size={16}/> Movimento</span><span><ShieldCheck size={16}/> Individualização</span></div><Link className="btn btn-dark" to="/tea">Conhecer essa abordagem <ArrowRight size={18}/></Link></div><div className="tea-pattern-card"><img src={teaImage} alt="Imagem da área de atividade física adaptada"/></div></div></section>
 {publishedPlans.length>0&&<section className="section deco-section"><div className="deco-icons"><span><Dumbbell/></span><span><Activity/></span><span><TimerReset/></span></div><div className="container"><SectionTitle eyebrow="PLANOS" title="Escolha a forma de acompanhamento ideal para você." text="Somente os planos publicados no painel aparecem aqui." center/><div className="plans-grid">{publishedPlans.map(plan=><article className={plan.featured?'plan-card featured':'plan-card'} key={plan.id}>{plan.promoText&&<span className="plan-badge">{plan.promoText}</span>}<h3>{plan.name}</h3><p>{plan.description||'Acompanhamento profissional personalizado.'}</p>{plan.price!=null&&<div className="plan-price">R$ {plan.price.toFixed(2)}</div>}<ul><li>{plan.sessions>0?`${plan.sessions} aulas/sessões`:'Consultoria mensal'}</li><li>{plan.durationDays} dias de acompanhamento</li></ul><Link to="/agendar" className="btn btn-primary">{plan.ctaText||'Quero este plano'}</Link></article>)}</div></div></section>}
 <section className="section deco-section"><div className="deco-icons"><span><Trophy/></span><span><Activity/></span><span><Dumbbell/></span></div><div className="container"><SectionTitle eyebrow="COMO FUNCIONA" title="Da primeira conversa à evolução." center/><div className="timeline">{[['01','Agendamento','Escolha um horário disponível.'],['02','Avaliação inicial','Entendimento de objetivos e rotina.'],['03','Planejamento','Estratégia individual e progressiva.'],['04','Acompanhamento','Ajustes e evolução ao longo do processo.']].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><p>{x[2]}</p></div>)}</div></div></section>
 <section className="section alt"><div className="container"><SectionTitle eyebrow="AVALIAÇÕES" title="Experiências compartilhadas." text="Avaliações novas passam por aprovação antes de aparecer publicamente."/><div className="reviews">{approved.slice(0,3).map(r=><article key={r.id}>{r.photo&&<img className="review-photo" src={r.photo} alt={r.name}/>}<div className="stars">{[1,2,3,4,5].map(i=><Star key={i} size={16} fill={i<=r.rating?'currentColor':'none'}/>)}</div><p>“{r.comment}”</p><b>{r.name}</b>{r.demo&&<span className="demo">DEMONSTRAÇÃO</span>}</article>)}</div><Link className="text-link" to="/avaliacoes">Ver e enviar avaliações <ArrowRight size={16}/></Link></div></section>
 <section id="faq" className="section"><div className="container faq-wrap"><SectionTitle eyebrow="FAQ" title="Perguntas frequentes."/><div className="faq-list">{store.faqs.filter(f=>!f.tea).map(f=><details key={f.id}><summary>{f.q}<span>+</span></summary><p>{f.a}</p></details>)}</div></div></section>
 <section className="cta-section"><div className="container cta-box"><div><span className="eyebrow">PRÓXIMO PASSO</span><h2>Seu próximo treino pode começar com uma boa conversa.</h2></div><Link to="/agendar" className="btn btn-primary btn-lg">Ver horários <CalendarCheck size={18}/></Link></div></section>
 </main><Footer store={store}/></>
}
